### ISSUE TITLE
The saved embed_tokens is empty

### ISSUE THREAD

**Issue by merlinarer** [AkariAsai/self-rag#21]
Hello, I try to run this code with llama1-7B, while I find the saved embed_tokens is empty and fail to load after training. Have you met this problem?
```
(Pdb) param_name
'model.embed_tokens.weight'
(Pdb) param
tensor([], dtype=torch.bfloat16)
```

**Comment by AkariAsai** [comment]
I haven't seen this issue on my side so I am not sure if I can help here... I had some issues when I was using Llama1 and adding special tokens a while ago, as back then (April or May) the HF transformers' llama1 support was somewhat unstable. Probably using Llama2 instead of upgrading HF transformers might help, although I am not sure...

**Comment by AkariAsai** [comment]
Yes we reduce the input_length for 13B due to the OOM issue, as mentioned in the paper. Let me upload the final 13B script and push it.

**Comment by AkariAsai** [comment]
I uploaded the 13B training script: [script_finetune_13b.sh](https://github.com/AkariAsai/self-rag/blob/main/retrieval_lm/script_finetune_13b.sh)
