### ISSUE TITLE
Why is retrieval dependent on only the previous span?

### ISSUE THREAD

**Issue by nightlessbaron** [AkariAsai/self-rag#7]
Hi, why is the input to the retrieval (x + y_(t-1)) and not (x +  y_(<t))
Also, a minor correction in the file name: `requirementd.txt` -> `requirements.txt`

<img width="1121" alt="image" src="https://github.com/AkariAsai/self-rag/assets/35189598/805d8618-a635-4b73-b470-330e95c885dd">

**Comment by AkariAsai** [comment]
We use the original input as well as the previous generation as a retrieval query (an input to the retrieval model) since if we use all previously generated sentences `y_{<t}`, the retrieved results are more biased towards earlier generations e.g., `y_1`, which might not be closely related to `y_t`, especially our generation gets longer. Figure 6 in [In-Context Retrieval-Augmented Language Models](https://arxiv.org/abs/2302.00083) also reports that once our retrieval queries get longer the model performance starts deteriorating. 
Note that our decision on whether we should retrieve is based on `y<t`, as indicated in the Table!

**Comment by nightlessbaron** [comment]
I see, thanks a lot for sharing this :D
